### ISSUE TITLE
Exception messages not printed

### ISSUE THREAD

**Issue by IAmMarcelJung** [FPGA-Research-Manchester/FABulous#148] opened 2024-02-02 10:38 UTC
Since #130, the exception message are not printed in the shell anymore. Since we already have logging, the exception message might also not be need and could therefore be removed. 

If we however need the messages, something like 
```
except Exception as e:
    print(e)
    return False
```
inside ```onecmd``` would again print the exception message. We should therefore decide if either omitting or printing the exception message is preferred.

IMHO it would be better to print the messages, but any other suggestions (also different ones to these two options) are welcome as always.

**Comment by KelvinChung2000** [comment] 2024-02-06 18:54
Printing the exception message will be better, as sometimes the cause of the error might be absent. Directly logging the error message will also be helpful.

**Comment by KelvinChung2000** [comment] 2024-02-16 10:52
fixed on #152

**Closed by KelvinChung2000** 2024-02-16 10:52 UTC
